### ISSUE TITLE
DIGITS5.1 - dev - In cpu mode

### ISSUE THREAD

**Issue by shixpGit** [NVIDIA/DIGITS#1535]
Hi，all.
I have refenced [https://github.com/NVIDIA/DIGITS/issues/251](url) to set a config to use digits in **cpu_only** mode. Like @fanser said , I also download DIGITS 5.1 source and NVIDIA/caffe master branch(0.15) from GitHub. Then I copy and rename Makefile.config.example , and uncomment CPU_ONLY :=1. And then, I build and runtest Caffe without error, but I still get those error messages when I created a model in digits:

_error messages:_
shixp@ubuntu:~/deep-learning/digits$ sudo ./digits-devserver 
**cudaRuntimeGetVersion() failed with error #35**
Couldn't import dot_parser, loading of dot files will not be possible.
2017-03-27 17:08:54 [INFO ] Loaded 2 jobs.
2017-03-27 17:09:07 [20170327-163021-4552] [INFO ] Job deleted.
2017-03-27 17:09:22 [20170327-170920-4fda] [DEBUG] Network sanity check - train
2017-03-27 17:09:22 [20170327-170920-4fda] [DEBUG] Network sanity check - val
2017-03-27 17:09:22 [20170327-170920-4fda] [DEBUG] Network sanity check - deploy
2017-03-27 17:09:22 [20170327-170920-4fda] [INFO ] Train Caffe Model task started.
2017-03-27 17:09:22 [20170327-170920-4fda] [INFO ] Task subprocess args: "**/usr/bin/caffe** 
train --solver=/home/shixp/deep-learning/digits/digits/jobs/20170327-170920-4fda/solver.prototxt"
2017-03-27 17:09:22 [20170327-170920-4fda] [ERROR] Train Caffe Model: Cannot create Cublas 
handle. Cublas won't be available.
2017-03-27 17:09:22 [20170327-170920-4fda] [ERROR] Train Caffe Model: Cannot create Curand generator. Curand won't be available.
2017-03-27 17:09:22 [20170327-170920-4fda] [ERROR] Train Caffe Model: Cannot create cuDNN 
handle. cuDNN won't be available.
2017-03-27 17:09:22 [20170327-170920-4fda] [ERROR] **Train Caffe Model: Check failed: error 
== cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version**
2017-03-27 17:09:23 [20170327-170920-4fda] [ERROR] Train Caffe Model task failed with error 
code -6

I wonder whether the caffe env path"/usr/bin/caffe" lead to this error?if it is, how to modify the 
configuration to use the version that I built?

OS:Ubuntu 14.04
digits:5.1 dev [](https://github.com/NVIDIA/DIGITS)
caffe:0.15 [](https://github.com/NVIDIA/caffe)

**Comment by lukeyeager** [comment]
> how to modify the configuration to use the version that I built?

https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md

> Then I copy and rename Makefile.config.example , and uncomment CPU_ONLY :=1.

Try the CMake build instead: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildCaffe.md#build

**Comment by shixpGit** [comment]
@lukeyeager Thanks a lot, but the problem still exists.
I have used **CMake build** and **added $CAFFE_ROOT**, which is
echo $CAFFE_ROOT
~/caffe_nv/build/tools/caffe:
~/caffe_nv/python/caffe/
,and I even modified 
~/digits/digits/config/caffe.py 
line 26: executable_dir : to absoulute path of my caffe/build/tools 
line 27: python_dir: to absoulute path of my caffe/python

whether I did wrong thing？

**Comment by shixpGit** [comment]
@lukeyeager I delete the caffe which may be made by BLVC/caffe in /usr/bin, then it works. 
 thanks a lot! : )
