### ISSUE TITLE
caffe installation inside digits-2.0 requires libcudart.so.6.5

### ISSUE THREAD

**Issue by GiuliaP** [NVIDIA/DIGITS#274]
Hi, I have downloaded digits-2.0 from NVIDIA's website and used the tarball installation. When I try to run the server (./runme.sh) I got the following error:
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Did you forget to "make pycaffe"?
Traceback (most recent call last):
  File "digits-devserver", line 39, in <module>
    config.load_config('quiet')
  File "/data/giulia/REPOS/digits-2.0/digits/digits/config/load.py", line 147, in load_config
    option.apply()
  File "/data/giulia/REPOS/digits-2.0/digits/digits/config/caffe_option.py", line 232, in apply
    import caffe
  File "/data/giulia/REPOS/digits-2.0/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/data/giulia/REPOS/digits-2.0/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: libcudart.so.6.5: cannot open shared object file: No such file or directory

It seems that caffe libraries inside digits-2.0 are linking against cuda-6.5 even if only the 7.0 libraries are provided... Is it possible or am I making some other mistake?

Giulia

**Comment by gheinrich** [comment]
Hi Giulia, you might want to re-install OpenCV if you already had a previous version installed. See #211.

**Comment by GiuliaP** [comment]
Thanks, it worked: I forgot to rebuild OpenCV after updating the CUDA Toolkit.

Giulia
