### ISSUE TITLE
'module' object has no attribute 'set_mode_gpu'

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#373]
This error gets thrown when classifying images through digits... Im guessing its arisen in the past few days?

**Comment by lukeyeager** [comment]
What version of caffe are you using? Did you build it with CUDA support?

```bash
$ ls build/lib/
_caffe.so       _caffe.so.0.13.2  libcaffe-nv.so.0.13    libproto.a
_caffe.so.0.13  libcaffe-nv.so    libcaffe-nv.so.0.13.2

$ ldd build/tools/caffe | grep cud
	libcudart.so.7.0 => /usr/local/cuda/lib64/libcudart.so.7.0 (0x00007f12c9e12000)
	libcurand.so.7.0 => /usr/local/cuda/lib64/libcurand.so.7.0 (0x00007f12c486b000)
	libcublas.so.7.0 => /usr/local/cuda/lib64/libcublas.so.7.0 (0x00007f12c28aa000)
	libcudnn.so.7.0 => /usr/local/cudnn/v3/lib64/libcudnn.so.7.0 (0x00007f12bf7f9000)
```

**Comment by RadicoLabs** [comment]
dev@SaveHive:~/caffe$ ls build/lib/
libcaffe-nv.a   libcaffe-nv.so.0       libcaffe-nv.so.0.13.1
libcaffe-nv.so  libcaffe-nv.so.0.13.0  libcaffe-nv.so.0.13.2
dev@SaveHive:~/caffe$ ldd build/tools/caffe | grep cud
        libcudart.so.7.0 => /usr/local/cuda/lib64/libcudart.so.7.0 (0x00007f0542225000)
        libcublas.so.7.0 => /usr/local/cuda/lib64/libcublas.so.7.0 (0x00007f053f52c000)
        libcurand.so.7.0 => /usr/local/cuda/lib64/libcurand.so.7.0 (0x00007f053bcc9000)
        libcudnn.so.7.0 => /usr/local/cuda/lib64/libcudnn.so.7.0 (0x00007f0536ebf000)
dev@SaveHive:~/caffe$

**Comment by lukeyeager** [comment]
1. Which version of DIGITS are you using?

2. Can you give me some more information about when/where this error is occuring? Screenshots? Logs?

**Comment by RadicoLabs** [comment]
Using DIGITS 2.3-dev... If its any consolation, i have an older version of DIGITS in use (2.1) that runs classification fine. This error seems to be output when i try any sort of classification whether it be from DIGITS or using the using the included example.py script....

This is the error being thrown:
```
Unknown file: solver.prototxt
Unknown file: train_val.prototxt
Traceback (most recent call last):
  File "/home/dev/Python/sched.py", line 62, in <module>
    main(jobID, strTime)
  File "/home/dev/Python/sched.py", line 55, in main
    schedule.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 367,                                                                              in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 64, i                                                                             n run_pending
    self._run_job(job)
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 96, i                                                                             n _run_job
    ret = job.run()
  File "/usr/local/lib/python2.7/dist-packages/schedule/__init__.py", line 293,                                                                              in run
    ret = self.job_func()
  File "/home/dev/Python/sched.py", line 27, in startJob
    flaggedImgs = use_archive.classify_with_archive(archive, devDir, use_gpu=Tru                                                                             e)
  File "/home/dev/Python/use_archive.py", line 75, in classify_with_archive
    mean_file=mean_file, labels_file=labels_file, use_gpu=use_gpu)
  File "/home/dev/Python/example.py", line 183, in classify
    net = get_net(caffemodel, deploy_file, use_gpu)
  File "/home/dev/Python/example.py", line 38, in get_net
    caffe.set_mode_gpu()
AttributeError: 'module' object has no attribute 'set_mode_gpu'
```

**Comment by lukeyeager** [comment]
Oh, this is in the `examples/classification` script? I thought you meant this was with the DIGITS webserver.

The example script doesn't mess with your PATH and PYTHONPATH to pull in the right version of Caffe like DIGITS does. Try this:

    python -c "import caffe; print caffe.__file__"

If you're pulling in the wrong version of Caffe, set your PYTHONPATH to the correct location.
```bash
export PYTHONPATH=$CAFFE_HOME/python:$PYTHONPATH
```

**Comment by RadicoLabs** [comment]
This error also gets thrown when trying to classify single images on the webserver... But i will give exporting the pythonPath a go :D

**Comment by RadicoLabs** [comment]
I fixed the problem.. Turns out my caffe files werent properly building because i forgot i tried to install a patch the other day that was erroring some of the files... Reinstalled and rebuilt Caffe and we're working fine!

How would one install [this](http://vision.princeton.edu/pvt/GoogLeNet/) then? Is it outdated or something ? THe files wont build in caffe for some reason

**Comment by lukeyeager** [comment]
> How would one install this then? Is it outdated or something ? THe files wont build in caffe for some reason

Discussion moved to #375. Thanks for moving the discussion of a new issue to a new thread!

**Comment by ShaharKatz** [comment]
For those of you that building caffe from scratch didn't fix the problem, caffe.'set_mode_gpu to caffe._caffe.set_mode_gpu fixed it. :)

**Comment by oscartheking** [comment]
In the python code, 

```
caffe_root = 'your_caffe_root'
sys.path.insert(0, caffe_root + 'python')  
import caffe  
caffe.set_device(0)
caffe.set_mode_gpu()
```

It will work.

**Comment by henanjun** [comment]
For me, i restart the jupyter is OK.

**Comment by ashj9** [comment]
> import sys import os caffe_root = 'your_caffe_root' sys.path.insert(0, caffe_root + 'python') import caffe caffe.set_device(0) caffe.set_mode_gpu()
Hi oscartheking, 
I tried above steps but didn't work out. Do you have any other suggestions? TIA

**Comment by oukohou** [comment]
Though may be late, but I encountered this same problem and found a way work around:

```
sys.path.insert(0, '/path/to/caffe/python')
import caffe
caffe.set_mode_gpu()
```
namely, add the caffe/pathon path to you sys.path before import caffe.
Wrote a [post here ](https://www.oukohou.wang/2019/01/16/reocrds_of_installation_errors_and_operations/#32-solution)for detailed analysis, hope helpful😁.
