### ISSUE TITLE
ImportError:libcurart.so.7.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by srepho** [NVIDIA/DIGITS#8]
I have followed the steps exactly as in your guide using an Amazon AWS GPU instance. When I get to the running of the `.\digit-server` I get: 

`Cannot guess value for "caffe_root": caffe binary cannot be found`
`Cannot guess value for "gpu_list": Cannot query GPUs without a valid caffe_root`

I also tried to download the .tar but when I run the `./runme` file and I get 

`ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory`

Do you have any suggestions about what I am doing wrong?

**Comment by lukeyeager** [comment]
Two suggestions:

1. You should use `digits-devserver` instead of `digits-server`. The devserver runs a user-level application, so you don't need root permissions for anything. This will also give you an interactive prompt for setting the configuration options.

2. Both of your issues seem to be regarding environment variables. You probably need to add these two lines to your .bashrc (but customized to match the installation on your machine, of course:

```
export CAFFE_ROOT=/home/username/caffe
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

**Comment by srepho** [comment]
Thanks so much - this has solved the issue.

**Comment by Saneesh** [comment]
For this error
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory

I have executed this command to solve it
sudo ldconfig /usr/local/cuda/lib64

**Comment by lakartoza** [comment]
@Saneesh Thank you! Solved mine

**Comment by Tejas-Khot** [comment]
@Saneesh 
I am still getting the same error in spite of the command you mentioned.
Could you please help.

**Comment by lukeyeager** [comment]
For those of you on Ubuntu 14.04 who have installed CUDA 7.0 or 7.5 with a .deb package, you can now solve this problem by installing the `cuda-ld-conf-7-0` package (or `cuda-ld-conf-7-5`, if you like).
```
$ apt-cache show cuda-ld-conf-7-0
Package: cuda-ld-conf-7-0
Depends: cuda-cudart-7-0, cuda-cublas-7-0, cuda-curand-7-0, cuda-license-7-0
Description: CUDA ld.so.conf files
 With this package, your programs will be able to find the CUDA shared
 libraries without editing the LD_LIBRARY_PATH environment variable.
```

You can follow [these instructions](https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/UbuntuInstall.md#repository-access) to get access to the repository that contains these packages.

**Comment by lukeyeager** [comment]
For more information, please see the "Environment" section of [docs/InstallCuda.md](https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCuda.md#environment).

**Comment by ParitoshParmar** [comment]
@Saneesh this is one of those life saving tips. Thanks a ton!

**Comment by ranju2015** [comment]
@Saneesh  Many Thanks. Solved my problem.

**Comment by NickShargan** [comment]
@Saneesh Thanks a lot. When I run **sudo ldconfig /usr/local/cuda/lib** (not for lib64) it became work.

**Comment by chrisranderson** [comment]
In case someone else runs into this... I got an error (something about `libcudnn.so is not a symbolic link` or something) when trying `ldconfig`. My directory looked like this:

![screenshot from 2016-10-07 07-38-55](https://cloud.githubusercontent.com/assets/5461398/19191915/97d09db0-8c61-11e6-973a-4f37917032d8.png)

See how the `libcudnn.so` files are duplicated instead of linked like the others? I deleted the first two, and then made it a chain of symbolic links like so:

```
sudo rm libcudnn.so
sudo rm libcudnn.so.5
sudo ln -s libcudnn.so.5.0.5 libcudnn.so.5
sudo ln -s libcudnn.so.5 libcudnn.so
```

I actually came here in search of fixing a TensorFlow problem - this ended up fixing it.

**Comment by lukeyeager** [comment]
@chrisranderson if you installed cuDNN with a deb package instead of with a tarball then you wouldn't run into this issue.

**Comment by chrisranderson** [comment]
@lukeyeager how do I do that?

**Comment by gheinrich** [comment]
@chrisranderson have a look at the [CUDA install doc](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/InstallCuda.md).

**Comment by monajalal** [comment]
@Saneesh  When I do that I get this for cuda8, what could have gone wrong?
```
$ sudo ldconfig /usr/local/cuda/lib64
[sudo] password for mona: 
/sbin/ldconfig.real: /usr/local/cuda/lib64/libcudnn.so.5 is not a symbolic link
```

**Comment by xnmp** [comment]
@Saneesh Bloody legend

**Comment by codeAshu** [comment]
Same case is with cuDNN 5.1. Follow the solution of @chrisranderson

**Comment by amir-shehzad** [comment]
thanks @Saneesh you saved my life

**Comment by famishedrover** [comment]
I have import error: ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory
with CUDA 9.0 
Tensorflow 1.5 


download https://developer.nvidia.com/rdp/cudnn-download   7.0.5 for cuda 9.0
sudo rm -rf /usr/local/cuda/include/cudnn.h
sudo rm -rf /usr/local/cuda/lib64/libcudnn*

cd 
cd cuda

sudo cp include/cudnn.h /usr/local/cuda/include/
sudo cp lib64/lib* /usr/local/cuda/lib64/
cd /usr/local/cuda/lib64/
sudo chmod +r libcudnn.so.7.0.5
sudo ln -sf libcudnn.so.7.0.5 libcudnn.so.7
sudo ln -sf libcudnn.so.7 libcudnn.so
sudo ldconfig
It works for me.

**Comment by englianhu** [comment]
```r
:~$ sudo apt-get install libcudnn*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libcudnn-dev' for glob 'libcudnn*'
Note, selecting 'libcudnn8-dev' for glob 'libcudnn*'
Note, selecting 'libcudnn7' for glob 'libcudnn*'
Note, selecting 'libcudnn8' for glob 'libcudnn*'
libcudnn8 is already the newest version (8.2.0.53-1+cuda11.3).
libcudnn-dev is already the newest version (7.6.5-0lambda1).
libcudnn7 is already the newest version (7.6.5-0lambda1).
The following packages were automatically installed and are no longer required:
  ledit libfindlib-ocaml libfindlib-ocaml-dev libldap2-dev ocaml-compiler-libs ocaml-findlib
  ocaml-interp ocaml-man ocaml-nox wine-stable wine-stable-amd64 wine-stable-i386:i386
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libcudnn8-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 0 B/582 MB of archives.
After this operation, 2,570 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
(Reading database ... 448004 files and directories currently installed.)
Preparing to unpack .../libcudnn8-dev_8.2.0.53-1+cuda11.3_amd64.deb ...
Unpacking libcudnn8-dev (8.2.0.53-1+cuda11.3) ...
dpkg: error processing archive /var/cache/apt/archives/libcudnn8-dev_8.2.0.53-1+cuda11.3_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libcudnn_static.a', which is also in package libcudnn-dev:amd64 7.6.5-0lambda1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libcudnn8-dev_8.2.0.53-1+cuda11.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

and then

```r
x [master]> use_condaenv("tf")
✓ [master]> library(tensorflow)
✓ [master]> hello <- tf$constant('Hello, TensorFlow!')
Error: Python module tensorflow was not found.

Detected Python configuration:

python:         /home/englianhu/anaconda3/bin/python3
libpython:      /home/englianhu/anaconda3/lib/libpython3.8.so
pythonhome:     /home/englianhu/anaconda3:/home/englianhu/anaconda3
version:        3.8.10 (default, May 19 2021, 18:05:58)  [GCC 7.3.0]
numpy:          /home/englianhu/.local/lib/python3.8/site-packages/numpy
numpy_version:  1.19.5
tensorflow:     /home/englianhu/.local/lib/python3.8/site-packages/tensorflow

NOTE: Python version was forced by RETICULATE_PYTHON
```
