### ISSUE TITLE
how to compile nvidia caffe fork with cudnn v5

### ISSUE THREAD

**Issue by David-Jin** [NVIDIA/DIGITS#962]
I want to install DIGITS from scratch.

I have 2 questions:
1. Does the nvidia caffe fork version 0.15.9 or nvdia caffe master support compiled with cudnn v5 ?
2. If it does support cudnn v5, how can i enable the feature in cmake project, because the document suggest to use Cmake to compile the project.
 I already know how to configure the feature in raw makefile, but no idea with cmake.

**Comment by gheinrich** [comment]
Hello, Nvidia Caffe 0.15.9 supports CuDNNv5. If you installed CuDNNv5 using `sudo apt-get install libcudnn5-dev` (see [prerequisites](libcudnn5-dev)) then Cmake will find it automatically.

You should not use the master branch of Nvidia Caffe.

**Comment by David-Jin** [comment]
Thanks, it works.
